### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by gmaclennan** [mafintosh/fs-blob-store#3]
https://github.com/mafintosh/fs-blob-store/blob/master/index.js#L11
`return path.join(root, path.resolve('/', dir))`

`path.resolve('/', 'relative/path')` returns `'C:\\relative\\path'` on windows, and the joined path becomes `C:\\my\\blobstore\\location\\C:\\relative\\path` which is not a valid path. I don't know enough about windows path separators in node to fix this in a PR.

**Comment by mafintosh** [comment]
thanks for reporting this. i'll try to get a friend with a windows box to debug it

**Comment by gmaclennan** [comment]
revisiting this if I understand correct the purpose of [index.js#L11](https://github.com/mafintosh/fs-blob-store/blob/master/index.js#L11) is to avoid accessing files outside the store path?

A windows-compatable solution would then be, I think:

``` js
return path.join(root, path.resolve('/', dir).replace(/^[a-zA-Z]:/, ''))
```

I don't have a windows box with node setup to test this easily (I found the error using electron and packaging for windows). Capturing lowercase and uppercase drive letters just in case [because this](https://github.com/nodejs/node-v0.x-archive/issues/7031). Windows only supports single-character drive letters so I think we're covered there.

**Comment by mafintosh** [comment]
@gmaclennan that fix looks good to me. could you pr it?
