### ISSUE TITLE
Callback never called

### ISSUE THREAD

**Issue by olalonde** [mafintosh/fs-blob-store#5]
It seems the callback is never called. Is that intentional? 

``` javascript
blobs.createWriteStream({
  key: 'some/path/file.txt'
}, console.log)
```

**Comment by olalonde** [comment]
Oops, missed that part `This method should return a writable stream, and call cb with err, metadata when it finishes writing the data to the underlying blob store.`

**Comment by mafintosh** [comment]
glad you figured it out! :)
